[package]
name = "matsuba"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "matsuba"
path = "matsuba.rs"

[dependencies]
x11rb = { version = "0.9.0", features = ["render"] }
fontconfig = { version = "0.5.0" }
freetype-rs = { version = "0.29.1" }
