[server]
listen_address = "[::1]:10000"

[keys]
henkan = "C-comma"
muhenkan = "C-period"
accept = "Return"
delete = "BackSpace"
cancel = "Escape"
next_conversion = "Tab"
prev_conversion = "S-Tab"

[theme]
# color of unselected entries
bg = "#333333"
fg = "#FFFFFF"

# color of currently selected entry
selected_bg = "#888888"
selected_fg = "#FFFFFF"

# color of the entry to be completed
completion_bg = "#AAAAAA"
completion_fg = "#333333"

[database]
cache_dir = "/usr/share/matsuba"
